###
POST  http://localhost:3000/api/notification
Content-Type: application/json

{
   "userId":6,
  "companyId":3,
  "notification":{"subject":"happy birthday","content":"We wish you a happy birthday"}
}
####
GET http://localhost:3000/api/notification/6